### ISSUE TITLE
qzCompressStream() fails to stream

### ISSUE THREAD

**Issue by rojkov** [intel/QATzip#39]
I'm having a problem very similar to #18, but for the case of HW compression.

It looks like `qzCompressStream()` compresses full data blobs only and cannot be used with streaming data.

My use case that fails:
I'm compressing a big file in smaller data blobs, setting last = 1 when the last blob is written. Then I'm de-compressing the compressed stream and comparing it to my original data. However, the reading stops already at the first smaller data blob I sent for compression.

The source code suggests that if `QzSessionParams_T.data_fmt` set to `QZ_DEFLATE_GZIP_EXT` (the default) then every data chunk is wrapped with a gzip header and footer.

Am I supposed to use `QZ_DEFLATE_RAW` for a session and to wrap the stream with a header and footer myself?

**Comment by feixuex** [comment]
> Am I supposed to use QZ_DEFLATE_RAW for a session and to wrap the stream with a header and footer myself?

I think so. If you are going to compress data as stream, you should call qzComrpess with session in which data_fmt is set QZ_DEFLATE_RAW and add header and footer manually.

**Comment by daweiq** [comment]
@rojkov The qzCompressStream() API is designed to support stream data compression in batch processing mode.
It will hold all data into the internal buffer until the buffer is full or last flag set. 
Then the input data will be sliced into chunks and sent to QAT device for compressing in parallel. 
The QATzip will put the compressed chunks in order and set the final bit only for the last chunk. 
```|Deflate 0 (BFIN = 0)| Deflate 1 (BFIN = 0)| ... |Deflate n  (BFIN = 1)|```
When software library receive the compressed data, it will keep decompressing until the end of 'Deflate n' 
block which has BFIN set. Because the software library thought it has reached the end of the stream when deflate 
block with BFIN set show. 

In your case, are your using software lib like zlib to decompress the compressed stream? 
And are you compressing the big file in smaller data blobs with qzCompressStream() API? 
If yes, the software library will stop decompressing at the data block with BFIN set. 
You can call deflate() again for the next blob and it will stop decompressing by the end of next block. 

To compress a big file, you can refer to the qzip utility 
[https://github.com/intel/QATzip/blob/master/utils/qzip.c](url)
which will call the qzCompress API to generate the GZIP block in the following format
```|GZIP extension header| Deflate (BFIN = 1)| GZIP footer|```
It follows the standard GZIP format defined in RFC1952 [https://tools.ietf.org/html/rfc1952](url)
So, other software like gzip can decompress it to the end of file.

**Comment by rojkov** [comment]
I'm implementing a [qatzip compression filter](https://github.com/intel/kubernetes-qat-envoy/blob/master/envoy_qatzip/compressor/qatzip_compressor_impl.cc) for [Envoy](https://www.envoyproxy.io/).

I've already implemented adding headers and footers in the filter. But it would be nice if QATzip added them itself in addition to setting `BFINAL` in the last Deflate block in the same fashion as  Zlib does unless it's bad for performance.

**Comment by daweiq** [comment]
It's not a performance issue while it's related to the definition of 'DEFLATE_RAW‘ format which is trying to provide more flexibility  to application developer to 

- Wrapper deflate blocks with GZIP header including extension fields defined by themselves. 

- Wrapper deflate blocks with other headers like 7zip 

As the output, QATzip will provide compressed deflate block and CRC checksum in the QzStream structure. 
For the detailed example please refer to the following function 
```
static ngx_int_t
ngx_http_qatzip_filter_end_stream(ngx_http_request_t *r,
    ngx_http_qatzip_ctx_t *ctx)
```
In file
[https://github.com/intel/asynch_mode_nginx/blob/master/modules/nginx_qatzip_module/ngx_http_qatzip_filter_module.c](url)

**Comment by mythi** [comment]
@daweiq 

> It's not a performance issue while it's related to the definition of 'DEFLATE_RAW‘ format which is trying to provide more flexibility to application developer to

I think @rojkov's original question was why `QZ_DEFLATE_GZIP_EXT` does not set the headers correctly but `QZ_DEFLATE_RAW` needs to be used and we have to include the headers ourselves.

> In your case, are your using software lib like zlib to decompress the compressed stream?

Yes. It's done for the validation purposes.

**Comment by daweiq** [comment]
@mythi 
The ```QZ_DEFLATE_GZIP_EXT``` format follow [RFC1952](https://tools.ietf.org/html/rfc1952) to add GZIP format including extension fields which can be decompressed by gzip.
The ```QZ_DEFALTE_RAW``` is deigned to provide more flexibility to user who can add customized header/footer.

**Comment by mythi** [comment]
> The `QZ_DEFLATE_GZIP_EXT` format follow RFC1952 to add GZIP format including extension fields which can be decompressed by gzip.

AFAIU, this did not work (reported in this issue) and we had to switch to `QZ_DEFLATE_RAW` and manage the headers ourselves

**Comment by daweiq** [comment]
Please try the qzip utility which is using ```QZ_DEFLATE_GZIP_EXT``` format and it works for me.
```
[root@qat-weiweiqi-dn1 utils]# ./qzip -k calgary
Reading input file calgary (3251493 Bytes)
Compressing...
Time taken:        5.245 ms
Throughput:     4959.379 Mbit/s
Space Savings:    60.876 %
Compression ratio: 2.556 : 1
[root@qat-weiweiqi-dn1 utils]# gunzip calgary.gz
gzip: calgary already exists; do you wish to overwrite (y or n)? y
[root@qat-weiweiqi-dn1 utils]# md5sum calgary*
3d00dfc38b130b5cd9faa0bde66fc61d  calgary
3d00dfc38b130b5cd9faa0bde66fc61d  calgary.bak
```

**Comment by mythi** [comment]
but qzip does not use `qzCompressStream()`

**Comment by daweiq** [comment]
Yes, qzip use qzCompress API which use ```QZ_DEFLATE_GZIP_EXT``` format. 
```qzCompressStream()``` using ```QZ_DEFLATE_RAW``` format.

**Comment by mythi** [comment]
> `qzCompressStream()` using `QZ_DEFLATE_RAW` format.

should `qzCompressStream()` be changed to not allow `QZ_DEFLATE_GZIP_EXT`?

**Comment by daweiq** [comment]
The problem is not with the format, it is way that QATzip support stream compression with stateless compression instead of the stateful compression. 
The stateless compression generate multiple deflate block in order and has the last block with BFIN set. 
```|Deflate 0 (BFIN = 0)| Deflate 1 (BFIN = 0)| ... |Deflate n (BFIN = 1)|```
So, regardless of ```QZ_DEFLATE_RAW``` or ```QZ_DEFLATE_GZIP_EXT``` format, the software decompression will stop at the end of 1st deflate block with BFIN set. 
In other words, even with ```QZ_DEFLAT_RAW``` format, if the file size is big than the ```strm_buff_sz``` in ```QzSessionParam```, 64KB as default, the decompression will stop at 64KB. 
So, to use qzCompressStream() compress the whole file, you have to set the ``` QzSessionParam.strm_buff_sz``` big enough to hold the file.
Or, use qzCompress() API as the sample in qzip utility.

**Comment by mythi** [comment]
@daweiq 

If I understand this correctly, the problem with `QZ_DEFLATE_GZIP_EXT` is as follows. Let's assume `strm_buff_sz` is too small for the data that gets streamed by the webserver:

we start with:
`GZIP header|Deflate 0 (BFIN = 0)| Deflate 1 (BFIN = 0)|...`

and buffer gets full so we get
`GZIP header|Deflate 0 (BFIN = 0)| Deflate 1 (BFIN = 0)|...|Deflate 1 (BFIN = 1)|GZIP footer`

with `QZ_DEFLATE_RAW` this becomes 

`Deflate 0 (BFIN = 0)| Deflate 1 (BFIN = 0)|...|Deflate 1 (BFIN = 1)|...|Deflate 0 (BFIN = 0)| Deflate 1 (BFIN = 0)|...|Deflate 1 (BFIN = 1)`

Correct?

and we deal with the GZIP headers. Our expectation was that `GZIP footer` gets added only when last bit is set and not when the buffer size gets full...

**Comment by daweiq** [comment]
@mythi  correct!

We cannot add ```GZIP footer``` for ```QZ_DEFLAT_RAW``` format as it's designed to let the user to add customerized GZIP or another header they want, sorry! 
Adding only the ```GZIP footer``` is very wired to users like Nginx, it's not a standard format. 
While, we do provide the CRC32 checksum in the QzStream structure returned by qzCompressStream() API.

**Comment by mythi** [comment]
> We cannot add `GZIP footer` for `QZ_DEFLAT_RAW` format as it's designed to let the user to add customerized GZIP or any other header they want, sorry!

That's fine and I understand this. The issue is that `qzCompressStream()` is not suitable for streaming with `QZ_DEFLATE_GZIP_EXT` because it adds `GZIP footer` to the stream before the stream ends (last = 1).

Could this be documented at least?

**Comment by daweiq** [comment]
While, I will call it limitation introduced by stateless compression.
We should document the limitation when using Stream API. 
Thank you for suggestion!
