### ISSUE TITLE
invalid compressed data--crc error

### ISSUE THREAD

**Issue by weeweetan** [intel/QATzip#65]
#### configure
qatzip_chunk_size 64k;
qatzip_stream_size 256k;
qatzip_buffers 16 8k;
#### file
size > 64k
#### mode
sw

**Comment by XingHongChenIntel** [comment]
hello weeweetan, Dose this issue is the same with (https://github.com/intel/asynch_mode_nginx/issues/59)?
we are trying to reproduce it and fix it.

**Comment by weeweetan** [comment]
These are two different issues，
qatzip_chunk_size 64K; 
qatzip_stream_size 64K;
file is ok，and file size is the same as "qatzip_chunk_size 64k;qatzip_stream_size 256k;"

**Comment by XingHongChenIntel** [comment]
hello @weeweetan :

Very thanks for raising this issue. For now, The Root cause have finished, and Fixed patch have finished also, we are in inner code reveiw process. This issue has the same root cause as the (https://github.com/intel/asynch_mode_nginx/issues/59).
So the patch will upload in the next release. 

if you have any concern, please let me know.

**Comment by XingHongChenIntel** [comment]
> [intel/asynch_mode_nginx#59](https://github.com/intel/asynch_mode_nginx/issues/59) compress is ok, qatzip_filter_module copies compressed data to the output chain with 8k less，this issue is related to crc32 calculation

yes, It will be compress right if you are in the HW path, but failed in SW callback, 
crc32 isssue is from "src/qatzip_sw.c" line 216, "*qz_sess->crc32 = crc32(*qz_sess->crc32, src, *src_len);"
it should change to " *qz_sess->crc32 = crc32(*qz_sess->crc32, src + total_in - current_loop_in, current_loop_in);"

**Comment by weeweetan** [comment]
yes，this bug is really not easy to appear, thanks for the feedback
