### ISSUE TITLE
two many log output with the swbackup=1 when stop qat service

### ISSUE THREAD

**Issue by guoanwu** [intel/QATzip#82]
1. stop the qat service by: service qat_service stop
2. test qatzip in the qatzip/test/ folder. 
./test -m 4 -l 1000 -t 1 -B 0 -D comp -L 1 -B 1

then you will see a lot of log output that will impact the performance, please remove the logs.

**Comment by XingHongChenIntel** [comment]
This is cause by the too many loops for test( when you set "-l 1000").
The error message is required, when QAT HW is down. so if you stop the qat service. we don't sugguest you set too many loops for test, because it's meanless, it will only get the sw fallback performance, it's no relative with QAT HW.

**Comment by guoanwu** [comment]
If we are using in the application. It will always see the log.

**Comment by daweiq** [comment]
QATzip will always try QAT offloading 1st by default. 
When QAT disabled,  we are rely on this log to tell user offloading is not enabled, compression will be slow.
